#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.3.3

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - which bundler
            - bundler -v
            - ls /usr/local/lib/ruby/gems/2.3.0/gems
            - rm -rf /usr/local/bin/bundler
            - rm -rf /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6
            - gem install --no-user-install bundler -v '2.0.1'
            - bundle install
            - ls /usr/local/lib/ruby/gems/2.3.0
            - ls /usr/local/lib/ruby/gems/2.3.0/gems
            - which bundler
            - bundle exec rspec
