image: ruby:2.3.3

pipelines:
  pull-requests::
    - parallel:
      - step:
          name: Test
          script:
            - gem install --no-user-install bundler -v '2.0.1'
            - bundler install
            - COVERALLS_DEBUG=true BITBUCKET_CI=true COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN bundler exec rspec
            - printenv
