#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.3.3

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - which bundler
            - bundler -v
            - rm -rf /usr/local/bin/bundler
            - gem install bundler -v '2.0.1'
            - bundle install
            - bundle exec rspec
